### ISSUE TITLE
For all of the tests make sure that happy and sad paths are broken down into their own tests

### ISSUE THREAD

**Issue by Courtney-Lippman** [daniabee/whats-cookin-good-lookin#72]
There are some devs that believe that tests should be broken down more. For example, the test 'Should be able to filter recipes by their name' tests for successful finds and a non-successful find. This could be broken down into 'Should be able to filter recipes by their name' and a second test such as 'Should not find a recipe by name if it doesn't match' or something like that. Discuss as a group and decide if this style fits your coding opinions.

**Comment by Courtney-Lippman** [comment]
I went through all of the tests for the recipeRepo class. I have decided not to push my changes up until Brett and I work on refactoring the filterByName and filterByTag methods. Depending on how we refactor those two methods, my tests for the recipeRepo may need to change.

**Comment by AndrewCerveny** [comment]
Ingredients had a single test for bad ingredient that wasn't be utilized I did delete it and made sure the test still passes all the other tested situations.
